application: demadatter
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  script: index.py

- url: /v1/.*
  script: v1.py

- url: /v2/.*
  script: v2.py

- url: /auth/.*
  script: twitter_oauth_handler.py




